# Grafana Datasources Configuration
# Pre-configured to read from Prometheus (Orthanc) and Graphite (Mercure)

apiVersion: 1

datasources:
  # Prometheus - Orthanc metrics
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus

  # Graphite - Mercure metrics
  - name: Graphite
    uid: graphite
    type: graphite
    access: proxy
    url: http://graphite:80
    editable: true
    jsonData:
      graphiteVersion: "1.1"
